# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80580450eb4f84c81ddb161cdafb4e3710e2ec9285775e00223ad2aa96e591c2d8abfe5a0f726df8f288de9fc3b3f0d5e11dcd40acd6d47d33a5ecb4b1851f0a

test:
  secret_key_base: d579ed30a6826631f99bd2e34cba86171247ba348a225680a904b58a84943aae2b1c3ee93926c51f307f8781bd8874689bcac0856b861677f59f86a7e1239cda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
